//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlockConverter.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BlockConverter.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Action if string is empty.
        /// </summary>
        public static string ActionIfEmptyStringPropertyValueConverter {
            get {
                return ResourceManager.GetString("ActionIfEmptyStringPropertyValueConverter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] AddBlockButton {
            get {
                object obj = ResourceManager.GetObject("AddBlockButton", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add Block after selected Blocks.
        /// </summary>
        public static string AddBlockToolTip {
            get {
                return ResourceManager.GetString("AddBlockToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Fail add blocks: .
        /// </summary>
        public static string AddedFailBlock {
            get {
                return ResourceManager.GetString("AddedFailBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add blocks successfully.
        /// </summary>
        public static string AddedSuccessfullyBlock {
            get {
                return ResourceManager.GetString("AddedSuccessfullyBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add.
        /// </summary>
        public static string AddPropertyValueConverter {
            get {
                return ResourceManager.GetString("AddPropertyValueConverter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add scheme fail: .
        /// </summary>
        public static string AddSchemeFailed {
            get {
                return ResourceManager.GetString("AddSchemeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add scheme successfully.
        /// </summary>
        public static string AddSchemeSuccessfully {
            get {
                return ResourceManager.GetString("AddSchemeSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Append .
        /// </summary>
        public static string AppendWordPropertyValueConverter {
            get {
                return ResourceManager.GetString("AppendWordPropertyValueConverter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Basic.
        /// </summary>
        public static string BasicGeneralSettings {
            get {
                return ResourceManager.GetString("BasicGeneralSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Begin.
        /// </summary>
        public static string BlockConstructionBegin {
            get {
                return ResourceManager.GetString("BlockConstructionBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cycle.
        /// </summary>
        public static string BlockConstructionCycle {
            get {
                return ResourceManager.GetString("BlockConstructionCycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на End.
        /// </summary>
        public static string BlockConstructionEnd {
            get {
                return ResourceManager.GetString("BlockConstructionEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на For.
        /// </summary>
        public static string BlockConstructionForCycle {
            get {
                return ResourceManager.GetString("BlockConstructionForCycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Function .
        /// </summary>
        public static string BlockConstructionFunction {
            get {
                return ResourceManager.GetString("BlockConstructionFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на If.
        /// </summary>
        public static string BlockConstructionIf {
            get {
                return ResourceManager.GetString("BlockConstructionIf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Input.
        /// </summary>
        public static string BlockConstructionInput {
            get {
                return ResourceManager.GetString("BlockConstructionInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Method .
        /// </summary>
        public static string BlockConstructionMethod {
            get {
                return ResourceManager.GetString("BlockConstructionMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Operation.
        /// </summary>
        public static string BlockConstructionOperation {
            get {
                return ResourceManager.GetString("BlockConstructionOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Output.
        /// </summary>
        public static string BlockConstructionOutput {
            get {
                return ResourceManager.GetString("BlockConstructionOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Post Cycle.
        /// </summary>
        public static string BlockConstructionPostCycle {
            get {
                return ResourceManager.GetString("BlockConstructionPostCycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string BlockConstructionPropertyBody {
            get {
                return ResourceManager.GetString("BlockConstructionPropertyBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Input.
        /// </summary>
        public static string BlockConstructionPropertyInput {
            get {
                return ResourceManager.GetString("BlockConstructionPropertyInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name.
        /// </summary>
        public static string BlockConstructionPropertyName {
            get {
                return ResourceManager.GetString("BlockConstructionPropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Output.
        /// </summary>
        public static string BlockConstructionPropertyOutput {
            get {
                return ResourceManager.GetString("BlockConstructionPropertyOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Return.
        /// </summary>
        public static string BlockConstructionReturn {
            get {
                return ResourceManager.GetString("BlockConstructionReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Switch.
        /// </summary>
        public static string BlockConstructionSwitch {
            get {
                return ResourceManager.GetString("BlockConstructionSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Clean Escape.
        /// </summary>
        public static string CleanEscapePropertyValueConverterName {
            get {
                return ResourceManager.GetString("CleanEscapePropertyValueConverterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] ConvertButton {
            get {
                object obj = ResourceManager.GetObject("ConvertButton", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Convert fail: .
        /// </summary>
        public static string ConvertStringToBlocksFailed {
            get {
                return ResourceManager.GetString("ConvertStringToBlocksFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Convert successfully.
        /// </summary>
        public static string ConvertStringToBlocksSuccessfully {
            get {
                return ResourceManager.GetString("ConvertStringToBlocksSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Convert code to Schemes.
        /// </summary>
        public static string ConvertToolTip {
            get {
                return ResourceManager.GetString("ConvertToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] CopyBlocksButton {
            get {
                object obj = ResourceManager.GetObject("CopyBlocksButton", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Copy fail: .
        /// </summary>
        public static string CopyBlocksFailed {
            get {
                return ResourceManager.GetString("CopyBlocksFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Copy successfully.
        /// </summary>
        public static string CopyBlocksSuccessfully {
            get {
                return ResourceManager.GetString("CopyBlocksSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Copy selected Blocks.
        /// </summary>
        public static string CopyBlocksToolTip {
            get {
                return ResourceManager.GetString("CopyBlocksToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Style .
        /// </summary>
        public static string CustomStyleName {
            get {
                return ResourceManager.GetString("CustomStyleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Dark.
        /// </summary>
        public static string DarkThemeName {
            get {
                return ResourceManager.GetString("DarkThemeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Default.
        /// </summary>
        public static string DefaultStyleName {
            get {
                return ResourceManager.GetString("DefaultStyleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на English.
        /// </summary>
        public static string enUSLanguage {
            get {
                return ResourceManager.GetString("enUSLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Export fail:.
        /// </summary>
        public static string ExportBlocksFailed {
            get {
                return ResourceManager.GetString("ExportBlocksFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Export successfully.
        /// </summary>
        public static string ExportBlocksSuccessfully {
            get {
                return ResourceManager.GetString("ExportBlocksSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No.
        /// </summary>
        public static string FalseTextBlock {
            get {
                return ResourceManager.GetString("FalseTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на General Settings.
        /// </summary>
        public static string GeneralSettingsHeader {
            get {
                return ResourceManager.GetString("GeneralSettingsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Language.
        /// </summary>
        public static string GeneralSettingsLanguage {
            get {
                return ResourceManager.GetString("GeneralSettingsLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Theme.
        /// </summary>
        public static string GeneralSettingsTheme {
            get {
                return ResourceManager.GetString("GeneralSettingsTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Input.
        /// </summary>
        public static string InputSampleForPropertyValueConverter {
            get {
                return ResourceManager.GetString("InputSampleForPropertyValueConverter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Insert.
        /// </summary>
        public static string InsertPropertyValueConverter {
            get {
                return ResourceManager.GetString("InsertPropertyValueConverter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Accept.
        /// </summary>
        public static string LanguageDialogAccept {
            get {
                return ResourceManager.GetString("LanguageDialogAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ignore.
        /// </summary>
        public static string LanguageDialogIgnore {
            get {
                return ResourceManager.GetString("LanguageDialogIgnore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reboot required to change app language.
        /// </summary>
        public static string LanguageDialogText {
            get {
                return ResourceManager.GetString("LanguageDialogText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Light.
        /// </summary>
        public static string LightThemeName {
            get {
                return ResourceManager.GetString("LightThemeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Thread.
        /// </summary>
        public static string LoggingThreadName {
            get {
                return ResourceManager.GetString("LoggingThreadName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add.
        /// </summary>
        public static string MenuAddBlockName {
            get {
                return ResourceManager.GetString("MenuAddBlockName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Convert to Blocks.
        /// </summary>
        public static string MenuConvertName {
            get {
                return ResourceManager.GetString("MenuConvertName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Copy.
        /// </summary>
        public static string MenuCopyBlocksName {
            get {
                return ResourceManager.GetString("MenuCopyBlocksName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New Scheme.
        /// </summary>
        public static string MenuCreateNewScheme {
            get {
                return ResourceManager.GetString("MenuCreateNewScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit.
        /// </summary>
        public static string MenuEditName {
            get {
                return ResourceManager.GetString("MenuEditName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Export to png.
        /// </summary>
        public static string MenuExportToPngName {
            get {
                return ResourceManager.GetString("MenuExportToPngName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File.
        /// </summary>
        public static string MenuFileName {
            get {
                return ResourceManager.GetString("MenuFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open.
        /// </summary>
        public static string MenuOpenName {
            get {
                return ResourceManager.GetString("MenuOpenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Paste.
        /// </summary>
        public static string MenuPasteBlocksName {
            get {
                return ResourceManager.GetString("MenuPasteBlocksName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Redo.
        /// </summary>
        public static string MenuRedoName {
            get {
                return ResourceManager.GetString("MenuRedoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Remove.
        /// </summary>
        public static string MenuRemoveBlockName {
            get {
                return ResourceManager.GetString("MenuRemoveBlockName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save as.
        /// </summary>
        public static string MenuSaveAsName {
            get {
                return ResourceManager.GetString("MenuSaveAsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings.
        /// </summary>
        public static string MenuSettingsName {
            get {
                return ResourceManager.GetString("MenuSettingsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Undo.
        /// </summary>
        public static string MenuUndoName {
            get {
                return ResourceManager.GetString("MenuUndoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name.
        /// </summary>
        public static string NameStyleColumnSettings {
            get {
                return ResourceManager.GetString("NameStyleColumnSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open fail: .
        /// </summary>
        public static string OpenBlockSchemeFailed {
            get {
                return ResourceManager.GetString("OpenBlockSchemeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open successfully.
        /// </summary>
        public static string OpenBlockSchemeSuccessfully {
            get {
                return ResourceManager.GetString("OpenBlockSchemeSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Output.
        /// </summary>
        public static string OutputSampleForPropertyValueConverter {
            get {
                return ResourceManager.GetString("OutputSampleForPropertyValueConverter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] PasteBlocksButton {
            get {
                object obj = ResourceManager.GetObject("PasteBlocksButton", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Paste fail: .
        /// </summary>
        public static string PasteBlocksFailed {
            get {
                return ResourceManager.GetString("PasteBlocksFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Paste successfully.
        /// </summary>
        public static string PasteBlocksSuccessfully {
            get {
                return ResourceManager.GetString("PasteBlocksSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Paste Blocks after selectsBlocks.
        /// </summary>
        public static string PasteBlocksToolTip {
            get {
                return ResourceManager.GetString("PasteBlocksToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Read laguage fail: .
        /// </summary>
        public static string ReadLaguageFailed {
            get {
                return ResourceManager.GetString("ReadLaguageFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Read laguage successfully.
        /// </summary>
        public static string ReadLaguageSuccessfully {
            get {
                return ResourceManager.GetString("ReadLaguageSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] RedoArrow {
            get {
                object obj = ResourceManager.GetObject("RedoArrow", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Redo.
        /// </summary>
        public static string RedoBlockToolTip {
            get {
                return ResourceManager.GetString("RedoBlockToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Redo fail: .
        /// </summary>
        public static string RedoFailed {
            get {
                return ResourceManager.GetString("RedoFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Redo successfully.
        /// </summary>
        public static string RedoSuccessfully {
            get {
                return ResourceManager.GetString("RedoSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Remove selected Blocks
        ///Ctrl+X.
        /// </summary>
        public static string RemoveBlockToolTip {
            get {
                return ResourceManager.GetString("RemoveBlockToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] RemoveButton {
            get {
                object obj = ResourceManager.GetObject("RemoveButton", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Fail remove blocks: .
        /// </summary>
        public static string RemoveFailBlock {
            get {
                return ResourceManager.GetString("RemoveFailBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Remove.
        /// </summary>
        public static string RemovePropertyValueConverter {
            get {
                return ResourceManager.GetString("RemovePropertyValueConverter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Remove scheme fail: .
        /// </summary>
        public static string RemoveSchemeFailed {
            get {
                return ResourceManager.GetString("RemoveSchemeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Remove scheme successfully.
        /// </summary>
        public static string RemoveSchemeSuccessfully {
            get {
                return ResourceManager.GetString("RemoveSchemeSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Remove blocks successfully.
        /// </summary>
        public static string RemoveSuccessfullyBlock {
            get {
                return ResourceManager.GetString("RemoveSuccessfullyBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Russian.
        /// </summary>
        public static string ruRULanguage {
            get {
                return ResourceManager.GetString("ruRULanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save fail: .
        /// </summary>
        public static string SaveBlockSchemeFailed {
            get {
                return ResourceManager.GetString("SaveBlockSchemeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save successfully.
        /// </summary>
        public static string SaveBlockSchemeSuccessfully {
            get {
                return ResourceManager.GetString("SaveBlockSchemeSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Accept.
        /// </summary>
        public static string SettingsAcceptCommand {
            get {
                return ResourceManager.GetString("SettingsAcceptCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] StartScheme {
            get {
                object obj = ResourceManager.GetObject("StartScheme", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Styles.
        /// </summary>
        public static string StylesSettingsHeader {
            get {
                return ResourceManager.GetString("StylesSettingsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Load BlockConverter is Successorfully.
        /// </summary>
        public static string SuccessorfullyInizializeRootViewModel {
            get {
                return ResourceManager.GetString("SuccessorfullyInizializeRootViewModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ctrl+B.
        /// </summary>
        public static string ToolTipBlock {
            get {
                return ResourceManager.GetString("ToolTipBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ctrl+R.
        /// </summary>
        public static string ToolTipCycleBlock {
            get {
                return ResourceManager.GetString("ToolTipCycleBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ctrl+E.
        /// </summary>
        public static string ToolTipEndBlock {
            get {
                return ResourceManager.GetString("ToolTipEndBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ctrl+F.
        /// </summary>
        public static string ToolTipForCycleBlock {
            get {
                return ResourceManager.GetString("ToolTipForCycleBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ctrl+T.
        /// </summary>
        public static string ToolTipIfBlock {
            get {
                return ResourceManager.GetString("ToolTipIfBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ctrl+I.
        /// </summary>
        public static string ToolTipInputBlock {
            get {
                return ResourceManager.GetString("ToolTipInputBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ctrl+M.
        /// </summary>
        public static string ToolTipMethodBlock {
            get {
                return ResourceManager.GetString("ToolTipMethodBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ctrl+O.
        /// </summary>
        public static string ToolTipOutputBlock {
            get {
                return ResourceManager.GetString("ToolTipOutputBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ctrl+P.
        /// </summary>
        public static string ToolTipPostCycleBlock {
            get {
                return ResourceManager.GetString("ToolTipPostCycleBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ctrl+K.
        /// </summary>
        public static string ToolTipSwitchBlock {
            get {
                return ResourceManager.GetString("ToolTipSwitchBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Yes.
        /// </summary>
        public static string TrueTextBlock {
            get {
                return ResourceManager.GetString("TrueTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] UndoArrow {
            get {
                object obj = ResourceManager.GetObject("UndoArrow", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Undo.
        /// </summary>
        public static string UndoBlockToolTip {
            get {
                return ResourceManager.GetString("UndoBlockToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Undo fail: .
        /// </summary>
        public static string UndoFailed {
            get {
                return ResourceManager.GetString("UndoFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Undo successfully.
        /// </summary>
        public static string UndoSuccessfully {
            get {
                return ResourceManager.GetString("UndoSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Union.
        /// </summary>
        public static string UnionPropertyValueConverterName {
            get {
                return ResourceManager.GetString("UnionPropertyValueConverterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Visual Converters.
        /// </summary>
        public static string VisualConvertersSettingsHeader {
            get {
                return ResourceManager.GetString("VisualConvertersSettingsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на , Connect to .
        /// </summary>
        public static string VisualPropertiesDirectionForAppendWord {
            get {
                return ResourceManager.GetString("VisualPropertiesDirectionForAppendWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Left.
        /// </summary>
        public static string VisualPropertiesLeftDirection {
            get {
                return ResourceManager.GetString("VisualPropertiesLeftDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Right.
        /// </summary>
        public static string VisualPropertiesRightDirection {
            get {
                return ResourceManager.GetString("VisualPropertiesRightDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  Word = .
        /// </summary>
        public static string VisualPropertiesWordName {
            get {
                return ResourceManager.GetString("VisualPropertiesWordName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Style.
        /// </summary>
        public static string VisualStyleColumnSettings {
            get {
                return ResourceManager.GetString("VisualStyleColumnSettings", resourceCulture);
            }
        }
    }
}
