//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelConverterToBlock {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ModelConverterToBlock.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add construction {0}. Start = {1}, lenght = {2}.
        /// </summary>
        internal static string ConverterContextAddConstructionMessage {
            get {
                return ResourceManager.GetString("ConverterContextAddConstructionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Find construction {0}. Start = {1}, lenght = {2}.
        /// </summary>
        internal static string ConverterContextFindConstructionMessage {
            get {
                return ResourceManager.GetString("ConverterContextFindConstructionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Find converter {0}.
        /// </summary>
        internal static string ConverterLinkWidthBodyFindConverterBody {
            get {
                return ResourceManager.GetString("ConverterLinkWidthBodyFindConverterBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Find converters.
        /// </summary>
        internal static string ConverterLinkWidthBodyFindConvertersBody {
            get {
                return ResourceManager.GetString("ConverterLinkWidthBodyFindConvertersBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Start body convert in property {0}.
        /// </summary>
        internal static string ConverterLinkWidthBodyStartConvertBody {
            get {
                return ResourceManager.GetString("ConverterLinkWidthBodyStartConvertBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add new property - {0}.
        /// </summary>
        internal static string ConverterSettingAddingNewGenerationPropertyMessage {
            get {
                return ResourceManager.GetString("ConverterSettingAddingNewGenerationPropertyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Filed to load converters from a file {0}.
        /// </summary>
        internal static string ConverterSettingFailedLoadPropertiesFromFileMessage {
            get {
                return ResourceManager.GetString("ConverterSettingFailedLoadPropertiesFromFileMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Load custom converters.
        /// </summary>
        internal static string ConverterSettingLoadCustomConverters {
            get {
                return ResourceManager.GetString("ConverterSettingLoadCustomConverters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Load default converters.
        /// </summary>
        internal static string ConverterSettingLoadDefaultConverters {
            get {
                return ResourceManager.GetString("ConverterSettingLoadDefaultConverters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Load converters from a file {0}.
        /// </summary>
        internal static string ConverterSettingLoadPropertiesFromFileMessage {
            get {
                return ResourceManager.GetString("ConverterSettingLoadPropertiesFromFileMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Not find some converters. Generation default....
        /// </summary>
        internal static string ConverterSettingNotFindConverters {
            get {
                return ResourceManager.GetString("ConverterSettingNotFindConverters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save converters for property.
        /// </summary>
        internal static string ConverterSettingPropertyConvertersSaveMessage {
            get {
                return ResourceManager.GetString("ConverterSettingPropertyConvertersSaveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel successfully.
        /// </summary>
        internal static string ConverterToBlockCancelConvertMessage {
            get {
                return ResourceManager.GetString("ConverterToBlockCancelConvertMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel successfully.
        /// </summary>
        internal static string ConverterToBlockCancelReadMessage {
            get {
                return ResourceManager.GetString("ConverterToBlockCancelReadMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Read Instructions successfully. Load laguage {0}.
        /// </summary>
        internal static string ConverterToBlockReadMessage {
            get {
                return ResourceManager.GetString("ConverterToBlockReadMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error: Not find instruction by function.
        /// </summary>
        internal static string ConvertToBlockFailedNotFindFunctionInstruction {
            get {
                return ResourceManager.GetString("ConvertToBlockFailedNotFindFunctionInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error: Language not laoded .
        /// </summary>
        internal static string ConvertToBlockFailedNotLoadLaguange {
            get {
                return ResourceManager.GetString("ConvertToBlockFailedNotLoadLaguange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Find {0} functions.
        /// </summary>
        internal static string ConvertToBlockFindFunction {
            get {
                return ResourceManager.GetString("ConvertToBlockFindFunction", resourceCulture);
            }
        }
    }
}
